name: Trigger PDF Build

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tech-memo-pdf workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PDF_REPO_TOKEN }}
          repository: your-username/tech-memo-pdf
          event-type: build-pdf
