name: Markdown to PDF

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # LaTeX をインストール
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-plain-generic

      # Pandoc をインストール
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # Markdown ファイルを PDF に変換
      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdf
          # 前回コミットとの差分で変更された md ファイルを処理
          for file in $(git diff --name-only HEAD^ HEAD | grep '\.md$' | grep -v 'README.md'); do
            filename=$(basename "$file" .md)
            pandoc "$file" -o "pdf/${filename}.pdf" \
              --pdf-engine=xelatex \
              -V geometry:a4paper \
              -V geometry:margin=15mm \
              -V mainfont="DejaVu Serif"
          done
