name: Markdown to PDF (All Files, Safe)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # 日本語フォントをインストール
      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho fonts-noto-cjk

      # LaTeX をインストール
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

      # Pandoc をインストール
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # PDF を全 Markdown ファイルから生成
      - name: Convert all Markdown to PDF
        run: |
          mkdir -p pdf
          find . -name '*.md' ! -name 'README.md' | while read file; do
            filepath=$(dirname "$file")
            filename=$(basename "$file" .md)
            mkdir -p "pdf/$filepath"
            pandoc "$file" -o "pdf/$filepath/${filename}.pdf" \
              --pdf-engine=xelatex \
              -V geometry:a4paper \
              -V geometry:margin=15mm \
              -V mainfont="Noto Serif CJK JP"
          done

      # PDF をリポジトリにコミット（無限ループ防止）
      - name: Commit PDF files safely
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pdf/
          # 差分がある場合のみ commit
          if ! git diff --cached --quiet; then
            git commit -m "Update PDFs from workflow [skip ci]"
            git push
          fi
