name: Markdown to PDF (B5, Gothic, Code Styled, BW)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # 日本語ゴシックフォントをインストール
      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-ipafont-gothic

      # LaTeX をインストール
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

      # Pandoc をインストール
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # PDF を全 Markdown ファイルから生成
      - name: Convert all Markdown to PDF
        run: |
          mkdir -p pdf
          find . -name '*.md' ! -name 'README.md' | while read file
          do
            filepath=$(dirname "$file")
            filename=$(basename "$file" .md)
            mkdir -p "pdf/$filepath"
            pandoc "$file" -o "pdf/$filepath/${filename}.pdf" \
              --pdf-engine=xelatex \
              -H code-style.tex \
              -V geometry:b5paper \
              -V geometry:top=12.7mm \
              -V geometry:bottom=12.7mm \
              -V geometry:left=12.7mm \
              -V geometry:right=12.7mm \
              -V mainfont="Noto Sans CJK JP" \
              -V fontsize=10pt \
              -V linestretch=1.3 \
              --lua-filter=bw-codeblock.lua
          done

      # PDF をリポジトリにコミット（競合は自動で最新版を優先）
      - name: Commit PDF files safely
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pdf/

          if ! git diff --cached --quiet; then
            # 競合時はリモートを優先して自動解決
            git commit -m "Update PDFs from workflow [skip ci]" || true
            git pull --rebase --strategy=recursive -X theirs origin main
            git push
          fi
