name: Markdown to PDF (All Files)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # texlive キャッシュ
      - name: Cache texlive
        id: cache-texlive
        uses: actions/cache@v4
        with:
          path: /usr/share/texlive
          key: ${{ runner.os }}-texlive-all-md
          restore-keys: |
            ${{ runner.os }}-texlive-

      # LaTeX をインストール（キャッシュされていない場合のみ）
      - name: Install LaTeX
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-plain-generic

      # Pandoc をインストール
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # Markdown を PDF に変換（全ファイル対象）
      - name: Convert all Markdown to PDF
        run: |
          mkdir -p pdf
          # リポジトリ内の全 .md ファイルを検索
          find . -name '*.md' ! -name 'README.md' | while read file; do
            # ディレクトリ構造を維持して PDF に変換
            filepath=$(dirname "$file")
            filename=$(basename "$file" .md)
            mkdir -p "pdf/$filepath"
            pandoc "$file" -o "pdf/$filepath/${filename}.pdf" \
              --pdf-engine=xelatex \
              -V geometry:a4paper \
              -V geometry:margin=15mm \
              -V mainfont="DejaVu Serif"
          done

      # PDF をアーティファクトとして保存
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-markdown-pdfs
          path: pdf/
