name: Markdown to PDF (B5, Gothic, Code Styled, BW)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-ipafont-gothic

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Create Lua filter
        run: |
          cat << 'EOT' > bw-codeblock.lua
-- Lua フィルター: fenced code blocks を codeblock 環境で出力
function CodeBlock(block)
  local lang = block.classes[1] or ""
  local content = block.text
  return pandoc.RawBlock('latex', string.format("\\begin{codeblock}\n%s\n\\end{codeblock}", content))
end
EOT

      - name: Convert all Markdown to PDF
        run: |
          mkdir -p pdf
          find . -name '*.md' ! -name 'README.md' | while read file; do
            filepath=$(dirname "$file")
            filename=$(basename "$file" .md)
            mkdir -p "pdf/$filepath"
            pandoc "$file" -o "pdf/$filepath/${filename}.pdf" \
              --pdf-engine=xelatex \
              -H code-style.tex \
              -V geometry:b5paper \
              -V geometry:top=12.7mm \
              -V geometry:bottom=12.7mm \
              -V geometry:left=12.7mm \
              -V geometry:right=12.7mm \
              -V mainfont="Noto Sans CJK JP" \
              -V fontsize=10pt \
              -V linestretch=1.3 \
              --lua-filter=bw-codeblock.lua

      - name: Commit PDF files safely
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pdf/
          
          if ! git diff --cached --quiet; then
            git commit -m "Update PDFs from workflow [skip ci]"
            git pull --rebase origin main
            git push
